# Generated by Django 3.2 on 2022-04-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_colours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_colours',
        ),
    ]
